// Plain website labels based on the app's lesson descriptions in src/seed/pack.
// Keep these separate from the generated brochure so sync:mobile preserves them.
export const lessonLabels: Record<string, string[]> = {
  panic_button: [
    "Why you feel worried before speaking",
    "Notice what you can see and hear",
    "Try moving when you feel nervous",
    "Check what you fear will happen",
    "Try stuttering on purpose in private",
    "Choose your first sentence",
    "Save your steps on a card",
  ],
  understanding_your_voice: [
    "The parts of stuttering others cannot see",
    "What causes stuttering",
    "Why your stutter can change",
    "Check what you were told about stuttering",
    "What happens when a word gets stuck",
    "The effort of avoiding words",
    "Choose where to start",
  ],
  breaking_thought_traps: [
    "A thought is not a fact",
    "Guessing what others think",
    "Worrying that everyone notices",
    "One hard moment does not explain everything",
    "Compare what you expect with what happens",
    "Notice what you do to avoid stuttering",
    "What to try when the thoughts return",
  ],
  art_of_disclosure: [
    "Find words to explain your stutter",
    "Try three ways to tell someone",
    "Practice with someone who already knows",
    "Try telling someone you do not know",
    "Respond to unwanted advice",
    "Talk about your stutter at the start",
    "Choose who to tell and what to share",
  ],
  word_swap: [
    "Notice the words you replace",
    "Notice when you choose a different word",
    "Try one word you often avoid",
    "Try speaking without planning each word",
    "Try stuttering on purpose on a chosen word",
    "Practice three words from your list",
    "Save your words on a card",
  ],
  bouncing_back: [
    "Why you keep thinking about a hard conversation",
    "Why your body still feels tense",
    "Write down what happened",
    "Hear another person's experience",
    "Talk to yourself as you would to a friend",
    "Review the conversation, then stop for the day",
    "Make a plan for after a hard conversation",
  ],
  dating_intimacy: [
    "When you cannot plan what to say",
    "Learn about talking about your stutter",
    "Decide what to share, if anything",
    "When you worry someone will reject you",
    "Guessing what the other person thinks",
    "Respond when someone finishes your sentence",
    "Plan conversations after the first date",
  ],
  interview_ready: [
    "Choose an interview to prepare for",
    "Practice a first call with a recruiter",
    'Answer "Tell me about yourself"',
    "Decide whether to mention your stutter",
    "Record and watch your answer",
    "Practice questions about your work",
    "Practice a full interview",
    "Practice longer answers",
    "Check your guesses about the interviewer",
    "Practice a word you often replace",
    "Practice with an interviewer who has less time",
    "Try another full interview",
    "Practice an interview with three people",
    "Save your notes and choose your next step",
  ],
  hard_conversations: [
    "Choose the calls you want to make",
    "Practice explaining a problem",
    "Respond when the answer is no",
    "Practice saying no",
    "Practice a friendly call without a plan",
    "Try a short conversation without planning",
    "Practice a call that matters to you",
    "Practice saying something personal",
    "Try a real call and save your notes",
  ],
  speech_toolkit: [
    "Notice what you already do when speaking",
    "Try a gentle start to a word",
    "Try keeping your voice going between words",
    "Practice taking a pause",
    "Break a long sentence into shorter parts",
    "Try easing tension when a word gets stuck",
    "Notice extra movements when you stutter",
    "Choose which speech tools to keep using",
  ],
};
